# =============================================================================
# generate_build_info.cmake
#
# 根据当前 Git 状态生成 build_info.h，仅在内容变化时才写入文件，避免触发
# 不必要的全量重编译。
#
# 入参（通过 -D 传入）:
#   WORKDIR    - Git 仓库工作目录（项目根）
#   DST_OUTPUT - 输出 build_info.h 的绝对路径
# =============================================================================

if(NOT DEFINED WORKDIR)
    message(FATAL_ERROR "generate_build_info.cmake: WORKDIR 未指定")
endif()
if(NOT DEFINED DST_OUTPUT)
    message(FATAL_ERROR "generate_build_info.cmake: DST_OUTPUT 未指定")
endif()

find_package(Git QUIET)

set(GIT_HASH   "unknown")
set(GIT_BRANCH "unknown")
set(GIT_DIRTY  0)

if(GIT_FOUND)
    # 短 commit hash（7 位）
    execute_process(
        COMMAND ${GIT_EXECUTABLE} rev-parse --short=7 HEAD
        WORKING_DIRECTORY ${WORKDIR}
        OUTPUT_VARIABLE _hash
        OUTPUT_STRIP_TRAILING_WHITESPACE
        RESULT_VARIABLE _r1
        ERROR_QUIET
    )
    if(_r1 EQUAL 0 AND NOT "${_hash}" STREQUAL "")
        set(GIT_HASH "${_hash}")
    endif()

    # 当前分支
    execute_process(
        COMMAND ${GIT_EXECUTABLE} rev-parse --abbrev-ref HEAD
        WORKING_DIRECTORY ${WORKDIR}
        OUTPUT_VARIABLE _branch
        OUTPUT_STRIP_TRAILING_WHITESPACE
        RESULT_VARIABLE _r2
        ERROR_QUIET
    )
    if(_r2 EQUAL 0 AND NOT "${_branch}" STREQUAL "")
        set(GIT_BRANCH "${_branch}")
    endif()

    # detached HEAD 时 abbrev-ref 会返回 "HEAD", 改用 describe 回退到 tag/commit
    if("${GIT_BRANCH}" STREQUAL "HEAD")
        execute_process(
            COMMAND ${GIT_EXECUTABLE} describe --all --always --dirty=
            WORKING_DIRECTORY ${WORKDIR}
            OUTPUT_VARIABLE _desc
            OUTPUT_STRIP_TRAILING_WHITESPACE
            RESULT_VARIABLE _r2b
            ERROR_QUIET
        )
        if(_r2b EQUAL 0 AND NOT "${_desc}" STREQUAL "")
            # 去除前缀 "heads/" 或 "remotes/"
            string(REGEX REPLACE "^(heads|remotes|tags)/" "" _desc "${_desc}")
            set(GIT_BRANCH "detached:${_desc}")
        else()
            set(GIT_BRANCH "detached")
        endif()
    endif()

    # 工作树是否有未提交修改
    execute_process(
        COMMAND ${GIT_EXECUTABLE} status --porcelain
        WORKING_DIRECTORY ${WORKDIR}
        OUTPUT_VARIABLE _status
        OUTPUT_STRIP_TRAILING_WHITESPACE
        RESULT_VARIABLE _r3
        ERROR_QUIET
    )
    if(_r3 EQUAL 0 AND NOT "${_status}" STREQUAL "")
        set(GIT_DIRTY 1)
    endif()
endif()

set(_new_content "/* Auto-generated by cmake/generate_build_info.cmake. DO NOT EDIT. */
#ifndef BUILD_INFO_H
#define BUILD_INFO_H

#define BUILD_GIT_HASH   \"${GIT_HASH}\"
#define BUILD_GIT_BRANCH \"${GIT_BRANCH}\"
#define BUILD_GIT_DIRTY  ${GIT_DIRTY}

#if BUILD_GIT_DIRTY
#define BUILD_GIT_SUFFIX \"+\"
#else
#define BUILD_GIT_SUFFIX \"\"
#endif

/* 形如 \"gabc1234\" 或 \"gabc1234+\"（dirty） */
#define BUILD_GIT_INFO   \"g\" BUILD_GIT_HASH BUILD_GIT_SUFFIX

#endif /* BUILD_INFO_H */
")

# 仅在内容变化时写入，避免触发整个项目重编译
set(_old_content "")
if(EXISTS ${DST_OUTPUT})
    file(READ ${DST_OUTPUT} _old_content)
endif()

if(NOT "${_old_content}" STREQUAL "${_new_content}")
    file(WRITE ${DST_OUTPUT} "${_new_content}")
    message(STATUS "build_info.h regenerated: branch=${GIT_BRANCH} hash=${GIT_HASH} dirty=${GIT_DIRTY}")
endif()
